export const USER_SET_TOKEN = "USER_SET_TOKEN";
export const USER_GET_TOKEN = "USER_GET_TOKEN";
export const USER_DELETE_TOKEN = "USER_DELETE_TOKEN";
export const USER_SET_ID = "USER_SET_ID";
export const USER_GET_OTP = "USER_GET_OTP";

export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const GET_LAWS = 'GET_LAWS';
export const FIND_LAW_BY_ID = 'FIND_LAW_BY_ID';

export const GET_JUDGEMENTS = 'GET_JUDGEMENTS';
export const FIND_JUDGEMENT_BY_ID = 'FIND_JUDGEMENT_BY_ID';

export const GET_SECTIONS = 'GET_SECTIONS';
export const FIND_SECTION_BY_ID = 'FIND_SECTION_BY_ID';